# Generated by Django 5.2.4 on 2025-07-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldestination',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='traveldestination',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
